version: '3.8'

services:
  mysql-auth:
    image: mysql:8.0
    container_name: pet-ez-mysql-auth
    environment:
      MYSQL_DATABASE: auth_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-auth-data:/var/lib/mysql
    networks:
      - pet-ez-network

  auth-service:
    build:
      context: ./Services/auth-service
      dockerfile: Dockerfile
    container_name: pet-ez-auth-service
    ports:
      - "3002:3002"
    environment:
      DATABASE_URL: mysql://root:root@mysql-auth:3306/auth_db
      JWT_SECRET: petez-super-secret-jwt-key-2024
    depends_on:
      - mysql-auth
    networks:
      - pet-ez-network

  booking-service:
    build:
      context: ./Services/booking-service
      dockerfile: Dockerfile
    container_name: pet-ez-booking-service
    ports:
      - "3006:3006"
    environment:
      DATABASE_URL: mysql://root:root@mysql-auth:3306/auth_db
      JWT_SECRET: petez-super-secret-jwt-key-2024
    depends_on:
      - mysql-auth
    networks:
      - pet-ez-network

  sitter-service:
    build:
      context: ./Services/sitter-service
      dockerfile: Dockerfile
    container_name: pet-ez-sitter-service
    ports:
      - "3004:3004"
    environment:
      DB_HOST: mysql-auth
      DB_NAME: auth_db
      DB_USER: root
      DB_PASSWORD: root
      JWT_SECRET: petez-super-secret-jwt-key-2024
      SESSION_SECRET: petez-super-secret-session-key-2024
    depends_on:
      - mysql-auth
    networks:
      - pet-ez-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: pet-ez-frontend
    ports:
      - "3001:3001"
    depends_on:
      - auth-service
    networks:
      - pet-ez-network

volumes:
  mysql-auth-data:

networks:
  pet-ez-network:
    driver: bridge